spring:
  application:
    name: TranzzoTask
  r2dbc:
    username: ${PGUSER:postgres}
    password: ${PGPASSWORD}
    url: r2dbc:postgresql://${PGHOST:localhost}:${PGPORT:5432}/${PGDATABASE:TranzzoDb}

  liquibase:
    enabled: true
    user: ${PGUSER:postgres}
    password: ${PGPASSWORD}
    change-log: classpath:/db.changelog/db.changelog-master.yaml
    url: jdbc:postgresql://${PGHOST:localhost}:${PGPORT:5432}/${PGDATABASE:TranzzoDb}?user=${PGUSER:postgres}&password=${PGPASSWORD}
    database-change-log-table: schema_history
    database-change-log-lock-table: schema_lock_history
    driver-class-name: org.postgresql.Driver

currencies-provider:
  url: ${SUPPLIER_URL:http://localhost:8081}
  fiat-api-key: ${FIAT_API_KEY:secret-key}

springdoc:
  show-actuator: true
  swagger-ui:
    enabled: true
    path: /user/swagger-ui/index.html
    url: /user/api-docs
  api-docs:
    path: /user/api-docs